version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: gTXhFhrDREanvyH9FgQ94DefWS8zXNuD
      MYSQL_DATABASE: glaucoma
      MYSQL_USER: glaucoma
      MYSQL_PASSWORD: zUrdVK3QbSU6YMbb23C2V2D4DA3nkZgx
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - frontend_data:/usr/share/nginx/html/frontend
      - backend_data:/usr/share/nginx/html/backend
  php-fpm:
    build:
      context: ./php
    volumes:
      - backend_data:/usr/share/nginx/html/backend

volumes:
  db_data:
  frontend_data:
  backend_data: