FROM nginx:latest

RUN apt update
RUN apt upgrade -y
RUN apt install -y git curl

RUN mkdir -p /usr/share/nginx/html/frontend
RUN mkdir -p /usr/share/nginx/html/backend

# Install nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - 
RUN apt install -y nodejs

# Build glaucoma service 
COPY glaucoma /usr/share/nginx/html/frontend
WORKDIR /usr/share/nginx/html/frontend
RUN npm install
RUN npm run build

# Remove nodejs
RUN apt remove nodejs -y

# Nginx confiuration file
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
COPY glaucoma.conf /etc/nginx/conf.d/glaucoma.conf