FROM nginx:latest

RUN apt update && apt install -y git

RUN mkdir -p /usr/share/nginx/html/frontend
RUN mkdir -p /usr/share/nginx/html/backend

# COPY id_rsa_frontend /root/.ssh/id_rsa_frontend
# RUN chmod 600 /root/.ssh/id_rsa_frontend
COPY frontend /usr/share/nginx/html/frontend

# COPY id_rsa_backend /root/.ssh/id_rsa_backend
# RUN chmod 600 /root/.ssh/id_rsa_backend

# RUN touch /root/.ssh/known_hosts
# RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

# RUN GIT_SSH_COMMAND="ssh -i /root/.ssh/id_rsa_frontend" git clone git@github.com:SaviorDT/glaucoma.git /usr/share/nginx/html/frontend
# RUN GIT_SSH_COMMAND="ssh -i /root/.ssh/id_rsa_backend" git clone git@github.com:SaviorDT/glaucoma_backend.git /usr/share/nginx/html/backend

# RUN apt install -y php8.2 php8.2-fpm php8.2-mysql php8.2-pgsql

COPY nginx.conf /etc/nginx/nginx.conf